### ISSUE TITLE
Fix incorrect warning log code

### ISSUE THREAD

**Issue by rickstaa** [rickstaa/crypto-listings-sniper#7]
The `binanceListingsChecker` contains code that is not correct:

https://github.com/rickstaa/crypto-listings-sniper/blob/05a751d7016f0f30838f64ba970d91aa802782be/exchanges/binanceListingsChecker/binanceListingsChecker.go#L49-L60

Here, the warning rate limit variable gets reset every time, while it should only be reset on the first trigger and after 1 minute.

**Comment by rickstaa** [comment]
Fixed in https://github.com/rickstaa/crypto-listings-sniper/releases/tag/v1.1.21.

**Comment by dekacypher** [comment]
Hi, I still receive this error even after installing the new version with zip file and updating the binance url
